name: Publish Packages
on:
  push:
    branches: [ master ]
    paths:
      - 'proto/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Generate stubs
      run: ./scripts/generate.sh

    - name: Publish Ruby Gem
      env:
        GEM_HOST_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ruby
        gem build telekeeper-grpc.gemspec
        gem push --key github --host https://rubygems.pkg.github.com/${{ github.repository_owner }}/

    - name: Publish Python Wheel
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        TWINE_REPOSITORY_URL: https://pypi.pkg.github.com/${{ github.repository_owner }}/
      run: |
        cd python
        pip install twine
        python -m build
        twine upload dist/*
